import Head from "next/head";
import Image from "next/image";
import Button from "../components/common/Button";
import TextInput from "../components/common/Inputs/TextInput";
import Header from "../containers/Header";
import Sidebar from "../containers/Sidebar";

export default function Home() {
  return (
    <div dir="rtl" id="yourAppElement">
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-row">
        <div className="w-2/12 h-screen">
        <Sidebar />
        </div>
        <div className="w-full">
          <Header title='داشبورد' />
          <TextInput
            title="نام کاربری"
            required
            type="text"
            placeholder="پارسا اسدپور"
          />
          <Button type="default">Primary</Button>
        </div>
      </div>
    </div>
  );
}
