import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../containers/Sidebar'

export default function Home() {
  return (
    <div dir='rtl' >
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Sidebar />
    </div>
  )
}
